### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by IvaSakharevych** [IvaSakharevych/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by IvannaSakharevych** [comment]
- Привіт!) Хотілося б сказати, що я мега крутий розробник з надзвичайними навиками до програмування, та я проста дівчина, якій хочеться такою стати. Подобається тестування, для мене це наче читати детективну історію. Люблю навчатися і завжди прагну до нових знань. Також подобається робити прості сайти (ще вчитися і вчитися), і бачити результат своє роботи. Я вірю, що жага до знань приведе мене куди потрібно!)
 - Hello!) I would like to say that I am a mega cool developer with extraordinary programming skills, but I'm just a girl who wants to be like that. I like testing, for me it's like reading a detective story. I love to study and always strive for new knowledge. I also like to make simple sites (still learn and learn), and see the result of my work. I believe that the thirst for knowledge will take me where I need to go!)
