### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by IvaSakharevych** [IvaSakharevych/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by IvannaSakharevych** [comment]
<section>
  <h3>Languages</h3>
  <p class="tags small"><a href="/uk-ua" hreflang="uk" rel="alternate" class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span></a> <a href="/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
</section>

<section>
  <h3>Skills</h3>
  <p class="tags small">
Basic Web Development (HTML/CSS, JavaScript),Photoshop illustrator, basics database
knowledge (MySQL) and software testing. </p>
</section>

<section>
  <h3>Character</h3>
  <p class="tags small">I like to study, consistent, executive, stubborn, responsible, sociable, I know how to work in a team, not conflicted.</p>
</section>

<section>
  <h3>Likes&#x1f603;</h3>
  <p class="tags small">People with a sense of humor, coffee, books, chocolate, needlework, embroidery, horses, cats and dogs, sincere people, summer, Lviv, fantasy and science fiction, detectives.</p>
</section>

<section>
  <h3>Dislikes&#x1f61e;</h3>
  <p class="tags small">When people make grammatical and spelling mistakes, egoists and egocentrists, superiority, irresponsibility and shifting responsibility to others, any manifestations of bullying, racism, violence, get sick and feel helpless...</p>
</section>

<section>
  <h3>Wants&#x1f97a;</h3>
  <p class="tags small bulleted">That close people, were healthy, less lazy, be more disciplined, travel, start running, get up at 5 am, walk in the rain in Paris, visit London, buy a car (such a red red), swim in the Dead Sea.</p>
</section>

<section>
  <h3>Education</h3>
  <ul class="timeline">
    <li>
      <div><em>December 2015</em></div>
      <div><strong>Certificate of Basics of Web UI development</strong> in <a href="https://courses.prometheus.org.ua/courses/LITS/104/2015_T4/course/" rel="external"><strong>Prometheus</strong></a></div>
    </li>
<li>
      <div><em>1<sup>st</sup> September 2012 &ndash; 31<sup>th</sup> December 2014</em></div>
      <div><strong>Specialist's degree</strong> in <strong>System Software</strong> at <a href="https://lpnu.ua/" rel="external"><strong>Lviv Polytechnic National University</strong></a></div>
    </li>
    <li>
      <div><em>1<sup>st</sup> September 2009 &ndash; 30<sup>th</sup> June 2012</em></div>
      <div><strong>Bachelor's degree</strong> in <strong>Software Engineering</strong> at <a href="https://lpnu.ua/" rel="external"><strong>Lviv Polytechnic National University</strong></a></div>
    </li>
    <li>
      <div><em>1<sup>st</sup> September 1998 &ndash; 31<sup>st</sup> May 2009</em></div>
      <div><strong>Certificate of complete general secondary education</strong> in <strong>Novomylyatyn secondary school №1</strong></div>
    </li>
  </ul>
</section>
